---
services:
  php:
    image: ${IMAGES_PREFIX:-}app-php
    restart: unless-stopped
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost}, php:80
      DEFAULT_URI: https://${SERVER_NAME:-localhost}:${HTTPS_PORT:-443}
      DATABASE_URL: postgresql://${POSTGRES_USER:-app}:${POSTGRES_PASSWORD:-!ChangeMe!}@database:5432/${POSTGRES_DB:-app}?serverVersion=18&charset=${POSTGRES_CHARSET:-utf8}
      MESSENGER_TRANSPORT_DSN: amqp://${RABBITMQ_USER:-hestia}:${RABBITMQ_PASSWORD:-hestia}@rabbitmq:5672/%2f/messages
      # The two next lines can be removed after initial installation
      SYMFONY_VERSION: ${SYMFONY_VERSION:-}
      STABILITY: ${STABILITY:-stable}
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - name: http
        target: 80
        published: ${HTTP_PORT:-80}
        protocol: tcp
      - name: https
        target: 443
        published: ${HTTPS_PORT:-443}
        protocol: tcp
      - name: http3
        target: 443
        published: ${HTTP3_PORT:-443}
        protocol: udp

  messenger:
    image: ${IMAGES_PREFIX:-}app-php
    restart: unless-stopped
    command: bin/console messenger:consume async scheduler_main --time-limit=3600 -vv
    depends_on:
      php:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      APP_ENV: ${APP_ENV:-dev}
      DATABASE_URL: postgresql://${POSTGRES_USER:-app}:${POSTGRES_PASSWORD:-!ChangeMe!}@database:5432/${POSTGRES_DB:-app}?serverVersion=18&charset=${POSTGRES_CHARSET:-utf8}
      MESSENGER_TRANSPORT_DSN: amqp://${RABBITMQ_USER:-hestia}:${RABBITMQ_PASSWORD:-hestia}@rabbitmq:5672/%2f/messages

  database:
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_USER: ${POSTGRES_USER:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:4.3-management-alpine
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-hestia}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-hestia}
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      timeout: 10s
      retries: 5
      start_period: 30s
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  caddy_data:
  caddy_config:
  database_data:
  rabbitmq_data:
