security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        main:
            lazy: true
            provider: app_user_provider
            entry_point: App\Security\JsonAuthenticationEntryPoint
            json_login:
                check_path: api_auth_login
                username_path: username
                password_path: password
                success_handler: App\Security\AuthenticationSuccessHandler
                failure_handler: App\Security\AuthenticationFailureHandler
            logout:
                path: api_auth_logout
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 7 days
                samesite: lax
                secure: true
            login_throttling:
                max_attempts: 5

    access_control:
        - { path: ^/api/internal/v1/auth/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/internal/v1/auth/csrf, roles: PUBLIC_ACCESS }
        - { path: ^/api/doc, roles: PUBLIC_ACCESS }
        - { path: ^/api/internal/v1, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # speed up tests
